Попытка сделать интерфейсы
OlegTimofeev/QueryProcessing pull request #8
Opened 2019-03-04 18:34 UTC by OlegTimofeev

Глянь, пожалуйста интерфейсы

2019-03-06 06:55 UTC, itimofeev requested changes

2019-03-06 06:55 UTC, itimofeev commented on requester.go
> +type Requester interface {
Синтаксис определения интерфейса норм, смысл немного неправильный.
По идее на вход он должен принимать описание задачи (*FetchTask), на выход отдавать ответ - объект, который описывает http ответ (status {ok, error}, contentLength, ...).

Интерфейс описывает то, что этот компонент умеет делать. Вспоминай пример с рулём. 
Интерфейс Руль {
  ПовернутьВлево(х градусов)
  ПовернутьВправо(х градусов)
}
А реализации могут быть разные (круглый руль, или как у мотика). Но всю машину не нужно переделывать, т.к. все остальные компоненты знают только, что руль умеет влево и вправо, а как он это делает, остальной системе пофиг.

2019-03-06 06:55 UTC, itimofeev commented on server.go
> +func (task FetchTask) send() string {
(!) Кстати, почитай, чем отличается FetchTask от *FetchTask

2019-03-06 06:55 UTC, itimofeev commented on server.go
> +	Id      string
1) Сюда тоже json наверное нужно
2) В go ID надо писать

2019-03-06 06:55 UTC, itimofeev commented on store.go
> +type Store interface {
Этот интерфейс должен реализовываться не FetchTask-ом. FetchTask это тупейший объект, который данные содержит. А логика по сохранению должна быть в другом компоненте. Опять же, чтобы можно было поменять реализацию только сохранения без переделки чего-либо в остальном коде.

2019-03-06 06:55 UTC, itimofeev commented on store.go
> +type Store interface {
Ну и описание методов немного поменяются, соответственно.

2019-03-14 07:46 UTC, itimofeev requested changes

2019-03-14 07:46 UTC, itimofeev commented on server.go
>  	Headers string `json:"headers"`
Headers должен иметь тип map[string]string. Т.е. у запросов может быть несколько заголовков. А заголовок это <key>: <value>

2019-03-14 07:46 UTC, itimofeev commented on server.go
>  var fetchTasks = make(map[string]FetchTask)
1. MapTool лучше переименовать в MapStore

1. fetchTasks должен лежать внутри MapStore. Почитай про инкапсуляцию. Все детали работы должны быть скрыты внутри объекта. Для реализации на базе данных, например, эта переменная вообще нафиг не нужна.

2019-03-14 07:46 UTC, itimofeev commented on server.go
>  func getTasks(c echo.Context) error {
Надо не map-у возвращать, а список просто.

2019-03-14 07:46 UTC, itimofeev commented on server.go
>  	_, ft := fetchTasks[taskId]
Хэндлеры должны работать с интерфейсом. Если ты напрямую к fetchTasks обращаешься, как ты потом заменишь эту реализацию на базу данных?

2019-03-14 07:46 UTC, itimofeev commented on server.go
> +func (rt RequesterTool) send(task FetchTask) string {
Ещё раз, почитай, чем *FetchTask от FetchTask. Если сам не вычитаешь, спроси у меня.

2019-03-14 17:39 UTC, OlegTimofeev commented on server.go
> +func (rt RequesterTool) send(task FetchTask) string {
Если передавать FetchTask как аргумент, то создаётся его копия, если *FetchTask то сможем менять значение этого таска в функции

2019-03-15 11:46 UTC, itimofeev commented on server.go
>  var fetchTasks = make(map[string]FetchTask)
А это решил не делать?

2019-03-15 11:47 UTC, itimofeev commented on server.go
>  func getTasks(c echo.Context) error {
Список объектов Store должен возвращать.

2019-03-15 11:47 UTC, itimofeev commented on server.go
>  	_, ft := fetchTasks[taskId]
И это тоже осталось.

2019-03-15 11:48 UTC, itimofeev commented on server.go
> +func (rt RequesterTool) send(task FetchTask) string {
Да, именно поэтому почти всегда нужно использовать со *. Ты же не хочешь, чтобы на каждый вызов данные копировались совершенно зазря?
Причём, как в параметрах функции, так и в func (rt *RequesterTool) send(task FetchTask) string

2019-03-15 12:04 UTC, itimofeev requested changes

2019-03-15 12:04 UTC, itimofeev commented on server.go
> +	guid := xid.New()
Генерацию айдишников лучше в стор как раз спрятать, чтобы клиенты не могли накосячить с неправильными айдишниками (повторяющимися, например)

2019-03-15 12:04 UTC, itimofeev commented on server.go
> +	guid := xid.New()
И ещё можно в одну строчку писать xid.New().String()

2019-03-15 12:04 UTC, itimofeev commented on server.go
> +	ms.fetchTasks[guid1.String()] = FetchTask{ID: guid1.String(), Request: "test1", Method: "GET", Body: "BODY"}
Это можно убрать уже наверное.

2019-03-15 12:04 UTC, itimofeev commented on server.go
> +	ms.fetchTasks = make(map[string]FetchTask)
Так не делается, блиин (((((((
Ну как ты будешь заменять реализацию на базу данных? Зачем там ей эта мапа будет, ну?
У стора отдельный метод должен быть, аля конструктор, NewMapStore() Store (тут именно интерфейс), а возвращает конкретную реализацию. Чтобы не было возможности влезть в детали внутренней реализации, как ты тут это делаешь.

2019-03-15 12:04 UTC, itimofeev commented on server.go
> +	ms.fetchTasks = make(map[string]FetchTask)
И там же инициализация внутренних переменных, типа этой мапы. В случае с БД будет соединение устанавливаться.

2019-03-15 12:04 UTC, itimofeev commented on server.go
>  	if err = c.Bind(&ft); err != nil {
Не увидел, откуда дёргается метод send и сохраняется его результаты?

2019-03-15 14:41 UTC, itimofeev requested changes

2019-03-15 14:41 UTC, itimofeev commented on server.go
> +type RequesterTool struct {
По задумке request-ер делает запросы, Store хранит данные. Лучше не смешивать две функции в одном компоненте. Отсюда следует, что ответы нужно хранить либо в отдельной мапе в Store, либо полем в FetchTask.

2019-03-15 14:41 UTC, itimofeev commented on server.go
> +func (ms *MapStore) init() {
Конструктор, это когда 
func NewMapStore() Store {
    return &MapStore{fetchTasks: make(map[]....)
}

2019-03-15 14:41 UTC, itimofeev commented on server.go
>  var ms MapStore
Это должны быть типы интерфейса, присвоенные из конструктора комментарием выше.

2019-03-15 14:41 UTC, itimofeev commented on server.go
> +		return &http.Response{}, err
Если возращаешь указатель, можно return nil, err делать.

2019-03-15 16:13 UTC, itimofeev approved these changes
Очень много мелких косяков из-за отсутствия опыта, который можно получить просматривая чужой код. Можешь мой проект посмотреть. Там есть свои нюансы, но какие-то моменты сможешь подметить, думаю. https://github.com/itimofeev/task2trip

На сегодня я уже устал, поэтому PR смёржу. Имей ввиду, что нужно будет чужой (например, мой) код посмотреть, иначе я задолбаюсь каждую запятую комментировать. Ну и оставшиеся замечания в следующем ПРе нужно будет поправить.

2019-03-15 16:13 UTC, itimofeev commented on server.go
> +	if err == nil {
Только в go наоборот делается:
if err != nil {
    // err handling
return если нужно
}

продолжение правильной обработки запроса.

2019-03-15 16:13 UTC, itimofeev commented on server.go
> +	if err != nil {
Для надёжности два раза?)))

2019-03-15 16:13 UTC, itimofeev commented on server.go
> +		var task = m.fetchTasks[id]
А хранить в мапе сразу указатели не удобнее будет?

2019-03-15 16:13 UTC, merged